# Generated by Django 2.2.7 on 2019-11-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gifs',
            new_name='Gif',
        ),
    ]
